{% set name = "pymsh" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymsh-{{ version }}.tar.gz
  sha256: 548cfe96697870435d1841c5cc7e2ce9137adcb1563595b9ae94e9b0d645fedc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pymsh
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: The Python multiset hashing library
  license: MIT
  license_file: LICENSE.md
  home: https://github.com/cgshep/pymsh


extra:
  recipe-maintainers:
    - cgshep
